apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  labels:
    storage: pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-50mi
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi 

---

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-c
    image: busybox
    command: ['sh', '-c', 'tail -f /dev/null']
    volumeMounts:
    - name: pvc-vol
      mountPath: /mnt/data
  volumes:
  - name: pvc-vol 
    persistentVolumeClaim:
      claimName: pvc-50mi
