apiVersion: v1
kind: Pod
metadata:
  name: test-vol
spec:
  containers:
  - image: busybox:1.28
    name: test-container
    command: ['sh','-c','tail -f /dev/null']
    volumeMounts:
    - mountPath: /app
      name: vol
  volumes:
  - name: vol
    emptyDir:
      sizeLimit: 500Mi
